### PR TITLE
Fixed defect where failed to download subtitle due to endoding issues.

### PR DESCRIPTION
**Pull request by nachomezzadra**
Tested it with Kody 14.2 for MacOS and OSMC 0.9.9 (raspberry pi).

### CODE REVIEW

**Comment by nachomezzadra** [comment]
Any chance to merge this fix?

**Comment by ramiro** [comment]
@nachomezzadra 

Does this mean the issue you are seeing (and trying to fix) is actually present in Kodi 14.x? In which Kodi version is that OSMC 0.9.9 based? The underlying platform is Linux. Right? 

Do you actually see problems in both these platforms?

For both platfoms:

What is the storage where the movies are located? A local filesystem? if so Of which type? A networked one? of which type?

**Comment by nachomezzadra** [comment]
@ramiro 

> Does this mean the issue you are seeing (and trying to fix) is actually present in Kodi 14.x? 

Yes, issue was present on Kodi v14.x running on MacOS.  

> In which Kodi version is that OSMC 0.9.9 based? 

OSMC doesn't really say what version it is based on.  It states that it is based on Kodi, but it doesn't say which version is based on.  

> The underlying platform is Linux. Right?

Yes, OSMC is based on a Linux Debian distro.

> Do you actually see problems in both these platforms?

Yes, issue is present in both platforms.

> What is the storage where the movies are located? A local filesystem? if so Of which type? A networked one? ow which type?

In the case of OSMC, movies are located on a network share (through Samba).  In the case of Kodi 14.x on MacOS, movies are located on the local hard disk.

**Comment by scambra** [comment]
This pull request has fixed issue for this subtitle:
plugin://service.subtitles.subdivx/?action=download&filename=%2fmedia%2ftorrent%2fseries%2fWayward%20Pines%2fWayward%20Pines%20-%20S01E10%20-%20Cycle.avi&id=X6XNDM2NDY2X-wayward-pines-s01e10

Using XBMC 13.2 from raspbmc

**Comment by ramiro** [comment]
I stil need to research this a bit more because I'm unable to reproduce this even when working with the reported problematic subtitles and I don't want to commit changes that fix things too specific to a platform/file system and risk breaking others.

I think this has been at least worked around partially in 3c90853

**Comment by ramiro** [comment]
Solved using another strategy by e8f0fe04cc656c8f00d125014e5dbffa6f7d083c.

**Pull request closed without merging**
